### ISSUE TITLE
Deck crashes client

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/cockatrice.github.io#23]
I had a user report the deck that has been attached crashes their client any time they try to load it into their deck editor. I was able to load the deck just fine and they said that they were able to manually edit it and after experimenting with several cards, they found if they removed Karmic Guide, the deck would load fine. I have attached their error log as well. I don't know if this is just specific to them or something that is an actual issue, so I figured I'd at least make y'all aware of it. Thank you.
[cockatriceerrorlog.txt](https://github.com/Cockatrice/cockatrice.github.io/files/4271040/cockatriceerrorlog.txt)
[AlesharistocratsCRASHWARNINGDONOTOPEN.zip](https://github.com/Cockatrice/cockatrice.github.io/files/4271042/AlesharistocratsCRASHWARNINGDONOTOPEN.zip)

**Comment by tooomm** [comment]
Thanks for reporting.

But this issue needs to be transferred to the correct repo (https://github.com/Cockatrice/Cockatrice) @ZeldaZach.

**Comment by D0nV170** [comment]
Oh crap. I didn't even realize I was on the wrong one >< I'll move everything and close this. Thanks.
